2017 May 30 Tue 17:33:51 INFO ==============
2017 May 30 Tue 17:33:51 INFO 接口名：/med
2017 May 30 Tue 17:34:09 INFO 参数：a=123;b=123
2017 May 30 Tue 17:34:30 INFO 响应异常：HTTPConnectionPool(host='192.168.1.8', port=6080): Max retries exceeded with url: /service?partnerId=20170315123001000001&systemVersion=3.4&service=%2Fmed&a=123&buildVersion=100&orderNo=JupbeqRyS0XiyeXDaaOb0M&system=python&sign=47e249780d11298f7c5e6891a2ddee13&deviceId=Python34&device=Python&b=123 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x023FF050>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
2017 May 30 Tue 17:34:30 INFO ==============
2017 May 30 Tue 17:34:34 INFO ==============
2017 May 30 Tue 17:34:34 INFO 接口名：/med
2017 May 30 Tue 17:34:48 INFO 参数：a=123;b=123
2017 May 30 Tue 17:35:10 INFO 响应异常：HTTPConnectionPool(host='192.168.1.8', port=6080): Max retries exceeded with url: /service?partnerId=20170315123001000001&systemVersion=3.4&service=%2Fmed&a=123&buildVersion=100&orderNo=xK8AilkAhaCmRUUeHu7Qbc&system=python&sign=6017764efb8b634dcd23e495a8bd9972&deviceId=Python34&device=Python&b=123 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x023EFFF0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))
2017 May 30 Tue 17:35:10 INFO ==============
